### ISSUE TITLE
Exercise03

### ISSUE THREAD

**Issue by NdrsPtrw** [OVGU-3DScanning-G2/Exercise#1]
TODOs:
* [x] thinning implementation
* [x] smoothing

**Comment by NdrsPtrw** [comment]
Möglicher bug:
Punkte im KD-Tree werden zwar markiert, ob sie ausgesiedet wurden, sind jedoch nicht unbedingt mit dem punkt-vektor synchronisiert

**Comment by oOWenderOo** [comment]
Aussage nicht ganz klar: Wo weden die Punkte markiert? Im thinning oder smoothing? Genauere Beschreibung bitte.

**Comment by NdrsPtrw** [comment]
Aktuell werden die Punkte beim thinning markiert.
Dafür haben Point3d einen bool thinnedOut bekommen.
warum das nicht funktioniert, ist wahrscheinlich, weil die Punkte, die im kd-tree sind markiert werden, nicht mit den Punkten im Vector verknüpft sind. 
Ideal wäre es, wenn im kd-tree nicht die Punkte aus dem Vektor kopiert sondern eine Referenz als Median abspeichert.

**Comment by oOWenderOo** [comment]
class KDTree
{
public:
	KDTree();
	KDTree(std::vector<Point3d>& points, int dim = 0);
	std::vector<Point3d> getRange(double laenge, Point3d& point, int dim);
	std::vector<Point3d> getKNN(Point3d& point, int k);
	std::vector<Point3d> smooth(std::vector<Point3d>& points, int strength);
	void thinning(std::vector<Point3d>& points, int strength);
	Point3d* median; <---------------------------------------------Pointer
	KDTree* left;
	KDTree* right;
protected:
	// dim: dimension to spit at
private:
	void getNN(Point3d& point, std::vector<Point3d>& neighbours, int k, int dim);
};


Also eigentlich sind die mediane als Pointer im KD-Tree gespeichert...
