### ISSUE TITLE
Einfärben der Punkte

### ISSUE THREAD

**Issue by oOWenderOo** [OVGU-3DScanning-G2/Exercise#3]
Die Punkte müssen nach dem Smoothing eingefärbt werden. Aktuell scheint die Verteilung der Farben noch nicht ideal zu sein. (d.h. die meisten änderunge sind eher gering, also < 0.001 und somit müssten die Grenzwerte für die Farben angepasst)

- [x] Einfärben der Punkte verbessern

- [ ] wer möchte kann die anderen Codeteile noch dokumentieren

**Comment by oOWenderOo** [comment]
Das Einfärben konnte ich verbessern. Hat sich also erledigt. Überzeugt mich aber noch nicht ganz :/

**Comment by NdrsPtrw** [comment]
Hi,
Leider ist bei den letzten commits etwas schief gegangen und die Anpassungen, dass es auf Linux läuft sind verloren gegangen.
hab das ganze wieder repariert und mir ist dabei ein recht interessanter git status bei raus gekommen: 

![Image of git status fail](https://s2.postimg.org/58m0ui089/git_status_fail.png)
